name: Deploy to Main Server

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the 'main' branch
  workflow_dispatch:  # Allows for manual deployment

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, mysqli, pdo, pdo_mysql
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile assets with Vite
        run: npm run build

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}  # Make sure this matches your server settings
          local-dir: './'
          server-dir: '/htdocs/'  # Target directory on the FTP server
          exclude: |
            **/.git*
            **/node_modules*
            **/tests*
            **/vendor*
            .env
            storage/logs/*
            storage/framework/sessions/*
            storage/framework/views/*
            storage/temp/*
            public/storage
          log-level: standard
          dry-run: false
