name: Deploy to FTP Server

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the 'main' branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'   # Adjust based on project needs
          extensions: mbstring, intl, mysqli, pdo, pdo_mysql
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}  # Default is usually 21; make sure this matches your server settings
          local-dir: './'
          server-dir: '/htdocs/'  # Target directory on the FTP server
          exclude: |
            **/.git*
            **/node_modules*
            **/tests*
            **/vendor*
            .env
            storage/logs/*
            storage/framework/sessions/*
            storage/framework/views/*
            storage/temp/*
            public/storage
          log-level: standard  # Choose from 'minimal', 'standard', or 'verbose'
          dry-run: false  # Set to 'true' for testing deployments without actual uploads
