name: Deploy to Test Server

on:
  push:
    branches:
      - test  # Deploy when changes are pushed to the 'test' branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, mysqli, pdo, pdo_mysql
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile assets with Vite
        run: npm run build

      - name: Upload via FTP to Test Server
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.FTP_HOST_TEST }}
          username: ${{ secrets.FTP_USERNAME_TEST }}
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          port: ${{ secrets.FTP_PORT_TEST }}  # Default is usually 21; adjust based on your server
          local-dir: './'
          server-dir: '/htdocs/'  # Specify your test directory on the FTP server
          exclude: |
            **/.git*
            **/node_modules*
            **/tests*
            **/vendor*
            .env
            storage/logs/*
            storage/framework/sessions/*
            storage/framework/views/*
            storage/temp/*
            public/storage
            .github
            Documentation
            CONTRIBUTING.md
            README.md
            SECURITY.md
            .gitattributes
            .github/workflows
            .gitignore
          log-level: standard
          dry-run: false  # Set to 'true' for a test run without deploying
